module Telegram
  module Bot
    module Types
      class Audio < Base
          attr_reader file_id: String
          attr_reader file_unique_id: String
          attr_reader duration: Integer
          attr_reader performer: String?
          attr_reader title: String?
          attr_reader file_name: String?
          attr_reader mime_type: String?
          attr_reader file_size: Integer?
          attr_reader thumbnail: PhotoSize?
      end
    end
  end
end
