module Telegram
  module Bot
    module Types
      class Chat < Base
        attr_reader id: Integer
        attr_reader type: String
        attr_reader title: String?
        attr_reader username: String?
        attr_reader first_name: String?
        attr_reader last_name: String?
        attr_reader is_forum: true?
        attr_reader photo: ChatPhoto?
        attr_reader active_usernames: Array[String]?
        attr_reader available_reactions: Array[ReactionTypeEmoji | ReactionTypeCustomEmoji]? # todo reemplazar por ReactionType
        attr_reader accent_color_id: Integer?
        attr_reader background_custom_emoji_id: String?
        attr_reader profile_accent_color_id: Integer?
        attr_reader profile_background_custom_emoji_id: String?
        attr_reader emoji_status_custom_emoji_id: String?
        attr_reader emoji_status_expiration_date: Integer?
        attr_reader bio: String?
        attr_reader has_private_forwards: true?
        attr_reader has_restricted_voice_and_video_messages: true?
        attr_reader join_to_send_messages: true?
        attr_reader join_by_request: true?
        attr_reader description: String?
        attr_reader invite_link: String?
        attr_reader pinned_message: Message?
        attr_reader permissions: ChatPermissions?
        attr_reader slow_mode_delay: Integer?
        attr_reader message_auto_delete_time: Integer?
        attr_reader has_aggressive_anti_spam_enabled: true?
        attr_reader has_hidden_members: true?
        attr_reader has_protected_content: true?
        attr_reader has_visible_history: true?
        attr_reader sticker_set_name: String?
        attr_reader can_set_sticker_set: true?
        attr_reader linked_chat_id: Integer?
        attr_reader location: ChatLocation?

      end
    end
  end
end
