module Telegram
  module Bot
    module Types
      class ChatPhoto < Base
        attr_reader small_file_id: String
        attr_reader small_file_unique_id: String
        attr_reader big_file_id: String
        attr_reader big_file_unique_id: String
      end
    end
  end
end
