module Telegram
  module Bot
    module Types
      class ChatPermissions < Base
      attr_accessor can_send_messages: bool?
      attr_accessor can_send_audios: bool?
      attr_accessor can_send_documents: bool?
      attr_accessor can_send_photos: bool?
      attr_accessor can_send_videos: bool?
      attr_accessor can_send_video_notes: bool?
      attr_accessor can_send_voice_notes: bool?
      attr_accessor can_send_polls: bool?
      attr_accessor can_send_other_messages: bool?
      attr_accessor can_add_web_page_previews: bool?
      attr_accessor can_change_info: bool?
      attr_accessor can_invite_users: bool?
      attr_accessor can_pin_messages: bool?
      attr_accessor can_manage_topics: bool?
      end
    end
  end
end
