module Telegram
  module Bot
    module Types
      module Compactable
        def to_compact_hash: () -> Hash[untyped, untyped]

        def to_json: (*untyped args) -> String
      end
    end
  end
end
