module Telegram
  module Bot
    module Types
      class Document < Base
          attr_reader file_id: String
          attr_reader file_unique_id: String
          attr_reader thumbnail: PhotoSize?
          attr_reader file_name: String?
          attr_reader mime_type: String?
          attr_reader file_size: Integer?
      end
    end
  end
end
