module Telegram
  module Bot
    module Types
      class ExternalReplyInfo < Base
          attr_reader origin:
              (MessageOriginUser |
                  MessageOriginHiddenUser |
                  MessageOriginChat |
                  MessageOriginChannel)
          attr_reader chat: Chat?
          attr_reader message_id: Integer?
          attr_reader link_preview_options: LinkPreviewOptions?
          attr_reader animation: Animation?
          attr_reader audio: Audio?
          attr_reader document: Document?
          attr_reader photo: Array[PhotoSize]?
          attr_reader sticker: Sticker?
          attr_reader story: Story?
          attr_reader video: Video?
          attr_reader video_note: VideoNote?
          attr_reader voice: Voice?
          attr_reader has_media_spoiler: true?
          attr_reader contact: Contact?
          attr_reader dice: Dice?
          attr_reader game: Game?
          attr_reader giveaway: Giveaway?
          attr_reader giveaway_winners: GiveawayWinners?
          attr_reader invoice: Invoice?
          attr_reader location: Location?
          attr_reader poll: Poll?
          attr_reader venue: Venue?
      end
    end
  end
end
