module Telegram
  module Bot
    module Types
      class ForceReply < Base
          attr_reader force_reply: true
          attr_reader input_field_placeholder: String?
          attr_reader selective: bool?
      end
    end
  end
end
