module Telegram
  module Bot
    module Types
      class KeyboardButtonRequestChat < Base
          attr_reader request_id: Integer
          attr_reader chat_is_channel: bool
          attr_reader chat_is_forum: bool?
          attr_reader chat_has_username: bool?
          attr_reader chat_is_created: bool?
          attr_reader user_administrator_rights: ChatAdministratorRights?
          attr_reader bot_administrator_rights: ChatAdministratorRights?
          attr_reader bot_is_member: bool?
      end
    end
  end
end
