module Telegram
  module Bot
    module Types
      class Location < Base
        attr_reader longitude: Float
        attr_reader latitude: Float
        attr_reader horizontal_accuracy: Float?
        attr_reader live_period: Integer?
        attr_reader heading: Integer?
        attr_reader proximity_alert_radius: Integer?
      end
    end
  end
end
