module Telegram
  module Bot
    module Types
      class Location < Base
        attr_accessor longitude: Float
        attr_accessor latitude: Float
        attr_accessor horizontal_accuracy: Float?
        attr_accessor live_period: Integer?
        attr_accessor heading: Integer?
        attr_accessor proximity_alert_radius: Integer?
      end
    end
  end
end
