module Telegram
  module Bot
    module Types
      class MaskPosition < Base
          attr_reader point: String
          attr_reader x_shift: Float
          attr_reader y_shift: Float
          attr_reader scale: Float
      end
    end
  end
end
