module Telegram
  module Bot
    module Types
      class MessageOriginHiddenUser < Base
        attr_reader type: 'hidden_user'
        attr_reader date: Integer
        attr_reader sender_user_name: String
      end
    end
  end
end
