module Telegram
  module Bot
    module Types
      class MessageOriginChat < Base
        attr_reader type: 'chat'
        attr_reader date: Integer
        attr_reader sender_chat: Chat
        attr_reader author_signature: String?
      end
    end
  end
end
