module Telegram
  module Bot
    module Types
      class Message < Base
        attr_reader message_id: Integer
        attr_reader message_thread_id: Integer?
        attr_reader from: User?
        attr_reader sender_chat: Chat?
        attr_reader date: Integer
        attr_reader chat: Chat
        attr_reader forward_origin: # MessageOrigin?
          (MessageOriginUser |
            MessageOriginHiddenUser |
            MessageOriginChat |
            MessageOriginChannel)?
        attr_reader is_topic_message: true?
        attr_reader is_automatic_forward: true?
        attr_reader reply_to_message: Message?
        attr_reader external_reply: ExternalReplyInfo?
        attr_reader quote: TextQuote?
        attr_reader via_bot: User?
        attr_reader edit_date: Integer?
        attr_reader has_protected_content: true?
        attr_reader media_group_id: String?
        attr_reader author_signature: String?
        attr_reader text: String?
        attr_reader entities: Array[MessageEntity]?
        attr_reader link_preview_options: LinkPreviewOptions?
        attr_reader animation: Animation?
        attr_reader audio: Audio?
        attr_reader document: Document?
        attr_reader photo: Array[PhotoSize]?
        attr_reader sticker: Sticker?
        attr_reader story: Story?
        attr_reader video: Video?
        attr_reader video_note: VideoNote?
        attr_reader voice: Voice?
        attr_reader caption: String?
        attr_reader caption_entities: Array[MessageEntity]?
        attr_reader has_media_spoiler: true?
        attr_reader contact: Contact?
        attr_reader dice: Dice?
        attr_reader game: Game?
        attr_reader poll: Poll?
        attr_reader venue: Venue?
        attr_reader location: Location?
        attr_reader new_chat_members: Array[User]?
        attr_reader left_chat_member: User?
        attr_reader new_chat_title: String?
        attr_reader new_chat_photo: Array[PhotoSize]?
        attr_reader delete_chat_photo: true?
        attr_reader group_chat_created: true?
        attr_reader supergroup_chat_created: true?
        attr_reader channel_chat_created: true?
        attr_reader message_auto_delete_timer_changed: MessageAutoDeleteTimerChanged?
        attr_reader migrate_to_chat_id: Integer?
        attr_reader migrate_from_chat_id: Integer?
        attr_reader pinned_message: MaybeInaccessibleMessage?
        attr_reader invoice: Invoice?
        attr_reader successful_payment: SuccessfulPayment?
        attr_reader users_shared: UsersShared?
        attr_reader chat_shared: ChatShared?
        attr_reader connected_website: String?
        attr_reader write_access_allowed: WriteAccessAllowed?
        attr_reader passport_data: PassportData?
        attr_reader proximity_alert_triggered: ProximityAlertTriggered?
        attr_reader forum_topic_created: ForumTopicCreated?
        attr_reader forum_topic_edited: ForumTopicEdited?
        attr_reader forum_topic_closed: ForumTopicClosed?
        attr_reader forum_topic_reopened: ForumTopicReopened?
        attr_reader general_forum_topic_hidden: GeneralForumTopicHidden?
        attr_reader general_forum_topic_unhidden: GeneralForumTopicUnhidden?
        attr_reader giveaway_created: GiveawayCreated?
        attr_reader giveaway: Giveaway?
        attr_reader giveaway_winners: GiveawayWinners?
        attr_reader giveaway_completed: GiveawayCompleted?
        attr_reader video_chat_scheduled: VideoChatScheduled?
        attr_reader video_chat_started: VideoChatStarted?
        attr_reader video_chat_ended: VideoChatEnded?
        attr_reader video_chat_participants_invited: VideoChatParticipantsInvited?
        attr_reader web_app_data: WebAppData?
        attr_reader reply_markup: InlineKeyboardMarkup?

        alias to_s text
      end

    end
  end
end
