module Telegram
  module Bot
    module Types
      class MessageOriginUser < Base
        attr_reader type: 'user'
        attr_reader date: Integer
        attr_reader sender_user: User
      end
    end
  end
end
