module Telegram
  module Bot
    module Types
      class PhotoSize < Base
          attr_reader file_id: String
          attr_reader file_unique_id: String
          attr_reader width: Integer
          attr_reader height: Integer
          attr_reader file_size: Integer?
      end
    end
  end
end
