module Telegram
  module Bot
    module Types
      class ReactionTypeCustomEmoji < Base
        attr_reader type: "custom_emoji"
        attr_reader custom_emoji_id: String
      end
    end
  end
end
