module Telegram
  module Bot
    module Types
      class SwitchInlineQueryChosenChat < Base
          attr_reader query: String?
          attr_reader allow_user_chats: bool?
          attr_reader allow_bot_chats: bool?
          attr_reader allow_group_chats: bool?
          attr_reader allow_channel_chats: bool?
      end
    end
  end
end
