module Telegram
  module Bot
    module Types
      class Update < Base
        attr_reader update_id: Integer
        attr_reader message: Message?
        attr_reader edited_message: Message?
        attr_reader channel_post: Message?
        attr_reader edited_channel_post: Message?
        attr_reader message_reaction: MessageReactionUpdated?
        attr_reader message_reaction_count: MessageReactionCountUpdated?
        attr_reader inline_query: InlineQuery?
        attr_reader chosen_inline_result: ChosenInlineResult?
        attr_reader callback_query: CallbackQuery?
        attr_reader shipping_query: ShippingQuery?
        attr_reader pre_checkout_query: PreCheckoutQuery?
        attr_reader poll: Poll?
        attr_reader poll_answer: PollAnswer?
        attr_reader my_chat_member: ChatMemberUpdated?
        attr_reader chat_member: ChatMemberUpdated?
        attr_reader chat_join_request: ChatJoinRequest?
        attr_reader chat_boost: ChatBoostUpdated?
        attr_reader removed_chat_boost: ChatBoostRemoved?

        def current_message: -> Base?
      end
    end
  end
end
