module Telegram
  module Bot
    module Types
      class User < Base
        attr_reader id: Integer
        attr_reader is_bot: bool
        attr_reader first_name: String
        attr_reader last_name: String?
        attr_reader username: String?
        attr_reader language_code: String?
        attr_reader is_premium: true?
        attr_reader added_to_attachment_menu: true?
        attr_reader can_join_groups: bool?
        attr_reader can_read_all_group_messages: bool?
        attr_reader supports_inline_queries: bool?
      end
    end
  end
end
