module Telegram
  module Bot
    module Types
      class Voice < Base
          attr_reader file_id: String
          attr_reader file_unique_id: String
          attr_reader duration: Integer
          attr_reader mime_type: String?
          attr_reader file_size: Integer?
      end
    end
  end
end
